version: '3'

services:

  nginx-lb:
    container_name: nginx-lb
    image: nginx:alpine
    restart: 'always'
    volumes:
      - confd_volume:/etc/nginx/conf.d
      - vhostd_volume:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - "./data/nginx-ssl:/etc/nginx/certs:ro"
    ports:
      - "80:80"
      - "443:443"

  nginx-config-generator:
    container_name: nginx-config-generator
    image: jwilder/docker-gen
    restart: 'always'
    volumes:
      - "./nginx-templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./data/nginx-ssl:/etc/nginx/certs:ro"
      - confd_volume:/etc/nginx/conf.d
      - vhostd_volume:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    command: -notify-sighup nginx-lb -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    depends_on:
      - "nginx-lb"

  letsencrypt-nginx-proxy-companion:
    container_name: letsencrypt-nginx-proxy-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: 'always'
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-config-generator
      - NGINX_PROXY_CONTAINER=nginx-lb
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/nginx-ssl:/etc/nginx/certs:rw"
      - confd_volume:/etc/nginx/conf.d
      - vhostd_volume:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    depends_on:
      - "nginx-config-generator"

  postgres:
    image: 'postgres:alpine'
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    restart: 'always'
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: replaceWithVeryLongPasswordForPGSQL
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
  
  keycloak:
    image: jboss/keycloak
    restart: 'always'
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: replaceWithVeryLongPasswordForPGSQL
      # COMMENT OUT TWO LINES BELOW AFTER THE FIRST START
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: replaceWithVeryLongPasswordForAdminUser
      PROXY_ADDRESS_FORWARDING: 'true'
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_DISCOVERY_PROPERTIES: datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=500,initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"
      VIRTUAL_HOST: id.example.com
      VIRTUAL_PORT: '8080'
      HTTPS_METHOD: redirect
      LETSENCRYPT_EMAIL: info@example.com
      LETSENCRYPT_HOST: id.example.com
    depends_on:
      - "postgres"

volumes:
  vhostd_volume:
  confd_volume:
  nginx_html:
  